# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#logic
arr[index] # indexing 1D

arr[inclusive:exclusive-1] # slicing 1D

arr[rows,cols] # 2D slicing

In [4]:
#slicing
arr[3:8]

array([3, 4, 5, 6, 7])

In [5]:
#get value using index position

arr[9]


9

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr[9:11]

array([ 9, 10])

In [6]:
#Get a value at an index
arr[2]

2

In [11]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [8]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [3]:
#Get values in a range
arr[0:5:3]

array([0, 3])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[4:8]=300
arr

array([  0,   1,   2,   3, 300, 300, 300, 300,   8,   9,  10])

In [6]:
#Setting a value with index range (Broadcasting)
arr[0:5]=900


arr

array([900, 900, 900, 900, 900, 300, 300, 300,   8,   9,  10])

In [60]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [19]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [ ]:
arr

Data is not copied, it's a view of the original array! This avoids memory problems!

In [41]:
#2D array-  Matrix
import numpy as np

a = np.array([[2, 4, 6, 8], [10, 20, 30, 40]])
print(a)



[[ 2  4  6  8]
 [10 20 30 40]]


In [43]:
id(a)

140461729869712

In [25]:
#logic for Matrix slicing
#[rows,cols]

a[1,3]


40

In [65]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [66]:
#[rows,cols]
arr[1,3:]

array([ 9, 10])

In [67]:
arr[1,1:4]

array([7, 8, 9])

In [68]:
a = np.array([[2, 4, 6, 8], [10, 20, 30, 40]])
print(a)

[[ 2  4  6  8]
 [10 20 30 40]]


In [71]:
a

array([[ 2,  4,  6,  8],
       [10, 20, 30, 40]])

In [ ]:
a[rows,cols]
rows[inclusive:exclsuive-1]

In [72]:
a[0:2,1:]

array([[ 2,  4,  6,  8],
       [10, 20, 30, 40]])

In [73]:
a[0:2,0:2]

array([[ 2,  4],
       [10, 20]])

In [74]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[11, 22, 33, 44, 55]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 22, 33, 44, 55]])

In [90]:

arr[0:3,3]

array([ 4,  9, 44])

In [57]:
arr[:2,2:3]

array([[3],
       [8]])

In [99]:
data = np.array([[11, 22, 33],
[44, 55, 66],
[77, 88, 99],
                [90, 81, 34]])
data

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99],
       [90, 81, 34]])

In [92]:
data[:3,2:3]

array([[33],
       [66],
       [99]])

In [65]:
data[2:3,2:]

array([[99]])

In [ ]:
33 66 99

In [ ]:
# [rows, cols]

In [ ]:
#Logic for slicing of 1D and 2D 

[incusive:exlcusive]-1D/Array

[rows,columns]- 2D/Matrix

In [100]:
arr=data

In [33]:
arr[:1,1:]

array([[2, 3, 4, 5]])

In [102]:
arr

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99],
       [90, 81, 34]])

In [103]:
arr[0::2,0:2]

array([[11, 22],
       [77, 88]])

In [101]:
arr[0:,0::2]

array([[11, 33],
       [44, 66],
       [77, 99],
       [90, 34]])

In [67]:
arr[0:,0::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 33, 55]])

In [12]:
arr[0][1]

2

In [36]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [16]:
# 7 4 10

arr[[1,0,1],[1,3,4]]

array([ 7,  4, 10])

In [72]:
arr[0: , 0:3 ]

array([[1, 2, 3],
       [6, 7, 8]])

In [78]:
arr[:,0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [42]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
arr[:,3:4]

array([[4],
       [9]])

In [84]:
arr[0:,3:4]

array([[4],
       [9]])

In [44]:
data = np.array([[11, 22, 33],
		[44, 55, 66],
		[77, 88, 99]])
data

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [45]:
data

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [101]:
data[1:3,1:3]

array([[55, 66],
       [88, 99]])

In [102]:
data[2:,0:]

array([[77, 88, 99]])

In [104]:
data[0::2,0:]

array([[11, 22, 33],
       [77, 88, 99]])

In [91]:
data[0:,:2]

# [[11 22]
#  [44 55]
#  [77 88]]



array([[11, 22],
       [44, 55],
       [77, 88]])

In [46]:
data

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [96]:
#[33 66 99]
data[0:,:-1]

array([[11, 22],
       [44, 55],
       [77, 88]])

In [46]:
data[1:3,1:]

array([[55, 66],
       [88, 99]])

In [19]:
a=[1, 2, 3, 4]
a[-1]

4

In [48]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [53]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12],
       [15, 16]])

In [58]:
arr[:,-1]

array([ 4,  8, 12, 16])

In [63]:
arr[:,-1:]

array([[ 4],
       [ 8],
       [12],
       [16]])

In [57]:
arr[1:2,1:4]

array([[6, 7, 8]])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [102]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [103]:
#Indexing row
arr_2d[1][2]


30

In [104]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [105]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [109]:
# Getting individual element value
arr_2d[1,0]

20

In [110]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [111]:
# 2D array slicing

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [112]:
arr_2d[2]

array([35, 40, 45])

In [113]:
arr_2d[2,:]

array([35, 40, 45])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [104]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
bool_arr=arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [81]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [106]:
arr[(arr > 4) & (arr <10)]

array([5, 6, 7, 8, 9])

In [110]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job!
