# Regular Expression

In [55]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
Salahuddin11@learnbay.com
321-555-4321
123.555.1234
123*555*-1234
123.555.1234
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''

In [54]:
'''
.       - Any Character Except New Line
\d      - Digit (0-9)
\D      - Not a Digit (0-9)
\w      - Word Character (a-z, A-Z, 0-9, _)
\W      - Not a Word Character
\s      - Whitespace (space, tab, newline)
\S      - Not Whitespace (space, tab, newline)

\b      - Word Boundary
\B      - Not a Word Boundary
^       - Beginning of a String
$       - End of a String

[]      - Matches Characters in brackets
[^ ]    - Matches Characters NOT in brackets
|       - Either Or
( )     - Group

Quantifiers:
*       - 0 or More
+       - 1 or More
?       - 0 or One
{3}     - Exact Number
{3,4}   - Range of Numbers (Minimum, Maximum)
'''

'\n.       - Any Character Except New Line\n\\d      - Digit (0-9)\n\\D      - Not a Digit (0-9)\n\\w      - Word Character (a-z, A-Z, 0-9, _)\n\\W      - Not a Word Character\n\\s      - Whitespace (space, tab, newline)\n\\S      - Not Whitespace (space, tab, newline)\n\n\x08      - Word Boundary\n\\B      - Not a Word Boundary\n^       - Beginning of a String\n$       - End of a String\n\n[]      - Matches Characters in brackets\n[^ ]    - Matches Characters NOT in brackets\n|       - Either Or\n( )     - Group\n\nQuantifiers:\n*       - 0 or More\n+       - 1 or More\n?       - 0 or One\n{3}     - Exact Number\n{3,4}   - Range of Numbers (Minimum, Maximum)\n'

In [92]:
import re

In [95]:
pattern = re.compile(r'M(r|s|rs)_[a-z]*')
pattern = re.compile(r'M(r|s|rs)(.|_)?\s*[A-Za-z][a-z]*')

match = pattern.finditer(text_to_search)

for i in match:
    print(i)

# match = pattern.findall(text_to_search)

<re.Match object; span=(259, 270), match='Mr. Schafer'>
<re.Match object; span=(271, 279), match='Mr Smith'>
<re.Match object; span=(280, 288), match='Ms Davis'>
<re.Match object; span=(289, 292), match='Mrs'>
<re.Match object; span=(303, 308), match='Mr. T'>
<re.Match object; span=(309, 317), match='Mr_hello'>


In [115]:
lst = ['akzelxw@hotmail.com',
'elum@@gmail.com', # invalid
'12345akbar.caakaterasu@gmail.com', # invalid
'akarui$kibuno@gmail.com', # invalid
'23545436@hotmail.com', # valid
'ajmeia@yahoo.com',
'ajhnstn87@gmail.com',
'ailuvzhoko4@hotmail.com',
'ailuvzhoko3@hotmail.com',
'ailuvzhoko2@hotmail.com',
'ailuvzhoko@hot123mail.com', # invalid
'aillensiquioco@aol.co.in', # valid
'ahmovic_ines@hotmail.com.in', # invalid
'ahmed__g300@yahoo.com', # invalid
'ahmadjazlan@gmail.com.com', # invalid
'ahmad_ridho19@yahoo.in'] # valid

# extract all the valid maild ids
# extract valid mail IDs only from gmail.com

In [140]:
pattern = '[A-Za-z.]+[0-9]*@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
match = [re.findall(pattern, email)  for email in lst]
print(match)

[['akzelxw@hotmail.com'], [], ['akbar.caakaterasu@gmail.com'], ['kibuno@gmail.com'], [], ['ajmeia@yahoo.com'], ['ajhnstn87@gmail.com'], ['ailuvzhoko4@hotmail.com'], ['ailuvzhoko3@hotmail.com'], ['ailuvzhoko2@hotmail.com'], ['ailuvzhoko@hot123mail.com'], ['aillensiquioco@aol.co.in'], ['ines@hotmail.com.in'], ['g300@yahoo.com'], ['ahmadjazlan@gmail.com.com'], ['ridho19@yahoo.in']]


In [141]:
pattern = re.compile("^[A-Za-z0-9]+_?[A-Za-z0-9]*@[A-Za-z]*\..*")
new_list = []
for i in list(filter(lambda x: len(pattern.findall(x)) > 0,lst)):
    if not('com.com' in i or 'com.in' in i):
        new_list.append(i)
print("===========VALID EMAIL LIST=============")        
print(new_list)
print()
print("===========GMAIL LIST=============")
gmail_list = list(filter(lambda x: '@gmail' in x,new_list))
gmail_list

===========VALID EMAIL LIST=============
['akzelxw@hotmail.com', '23545436@hotmail.com', 'ajmeia@yahoo.com', 'ajhnstn87@gmail.com', 'ailuvzhoko4@hotmail.com', 'ailuvzhoko3@hotmail.com', 'ailuvzhoko2@hotmail.com', 'aillensiquioco@aol.co.in', 'ahmad_ridho19@yahoo.in']

===========GMAIL LIST=============


['ajhnstn87@gmail.com']

# Numpy -> Numerical Python

In [73]:
import numpy as np)

In [64]:
lst = [1,2,3,4,5]
arr = np.array(lst)

print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [65]:
print(arr.size)

5


In [66]:
print(arr.shape)

(5,)


In [68]:
print(arr.ndim) # Dimention 

1


In [69]:
lst = [[1,2,3,4,5], [6,7,8,9,10]]
arr = np.array(lst)

In [70]:
print(arr.shape)

(2, 5)


In [71]:
print(arr.ndim)

2


In [75]:
np.arange(36).reshape(4,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [76]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# Linspace

In [78]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

# Zeros and Zeros like

In [83]:
np.zeros((2,4,3), dtype = int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
lst = [[1,2], [3,4], [5,6]]
arr = np.array(lst)

np.zeros_like
np.ones
np.ones_like

In [85]:
np.identity(4, dtype= int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])