In [ ]:
# enter the amount
# if the amount is less than 50000 then tell that the amount deposited

{
# if the amount is btw 50000 -- 70000 I want you to raise an error_1
# If the error_1 is raise then ask for pan 

# If the len of pan number is 10 ---> amount deposited
# else raise an error and stop every
}

# If the amont is greater than the 70000 raise and error Over_limit
# if the over limit error is raised ,
# Ask if they want to retry from begining
# if Y then do same thing prviously done


# If N then stop


# Log all the steps as well as errors 

In [11]:
class HighAmountError(Exception):
    def __init__(self, msg):
        self.msg = msg
        
        
class OverLimitError(Exception):
    def __init__(self, msg):
        self.msg = msg
        
        
class PANError(Exception):
    def __init__(self, msg):
        self.msg = msg
        
        
class StopError(Exception):
    def __init__(self, msg):
        self.msg = msg

In [12]:

f = open('file_handling/bank_records.txt' , 'w')

def Bank_Transfer():
    amount = eval(input('Please enter the amount you want to transfer: '))
    f.write(str(amount))
    try:
        if amount >= 0 and amount <= 50000:
            print('Amount transferred')
            f.write(str('\nAmount transferred'))
        elif amount >= 50000 and amount <= 70000:
            raise HighAmountError ('Please give your PAN number')
        elif amount >= 70000:
            raise OverLimitError ('The amount entered is more than the maximum limit of transaction!')
    except HighAmountError as e:
        try:
            f.write(f'\n{str(e)}')
            PAN_number = input('Please give your PAN number: ')
            if len(PAN_number) == 10:
                print('Amount transferred')
            else:
                raise PANError ('Wrong PAN number!')
        except PANError as e:
            f.write(f'\n{str(e)}')
            raise StopError('Please try after sometime')
                
    except OverLimitError as e:
        f.write(f'\n{str(e)}')
        retry = input('Do you want to try with a less amount? Y/N: ')
        f.write(str(retry))
        if retry == 'Y':
            f.write(str('\nGoing for a retry'))
            Bank_Transfer()
        elif retry == 'N':
            print('Have a good day!')
    
    finally:
        f.close()
    
Bank_Transfer()



Please enter the amount you want to transfer: 55000
Please give your PAN number: 123


StopError: Please try after sometime

In [17]:
class error_1(Exception):
    def __init__(s,msg):
        s.msg = msg
        
class error_2(Exception):
    def __init__(s,msg):
        s.msg = msg
        
class error_3(Exception):
    def __init__(s,msg):
        s.msg = msg        
        
def enter_amt():
    return input('Enter an amount to deposit. ')

def enter_pan():
    return input('Enter PAN number. ')

def logs(m):
    with open('bank_logs.txt','w') as f:
        f.write(str(m))

def start():

        amt = enter_amt()
        if eval(amt) < 50000:
            logs(f'Amount Deposit --> {amt}\nThanks for using COD')
            return f'Amount Deposit --> {amt}\nThanks for using COD'
        if eval(amt) >= 50000 and eval(amt) <= 70000:
            return f'error_1-{amt}'
        if eval(amt) > 70000:
            return f'error_over_limit-{amt}'



while 1:
    try:
        c = input('Enter "y" to start COD or "n" to exit. ')
        
        if c.lower() == 'y':
            global a 
            a = start()
            if a.split('-')[0] == 'error_1':
                raise error_1('PAN is required for Amount greater than or equal to 50000 ')
            elif a.split('-')[0] == 'error_over_limit':
                raise error_2(f'Amount - {a.split("-")[1]} Overlimit\nUnable to deposit')
            else:
                print(a)
                break
        elif c.lower() == 'n':
            raise error_2('Thanks for using COD')
        else:
            print('Not a valid option. Please enter correct option')

    except error_2 as e:
        logs(e)
        print(e)
        break
    except error_1 as e1:
        logs(e1)
        print(e1)
        pan_details = enter_pan()
        try:
            if len(pan_details) == 10:
                logs(f'Amount Deposit --> {a.split("-")[1]}\nThanks for using COD')
                print(f'Amount Deposit --> {a.split("-")[1]}\nThanks for using COD')
                break
            else:
                raise error_3(f'Invalid PAN number {pan_details}\nDo you want to continue? ')
                break

        except error_3 as e3:
            logs(e3)
            print(e3)

Enter "y" to start COD or "n" to exit. 60000
Not a valid option. Please enter correct option
Enter "y" to start COD or "n" to exit. y
Enter an amount to deposit. 60000
PAN is required for Amount greater than or equal to 50000 
Enter PAN number. 1234567894
Amount Deposit --> 60000
Thanks for using COD


# Regular expression

In [ ]:
'''
.       - Any Character Except New Line
\d      - Digit (0-9)
\D      - Not a Digit (0-9)
\w      - Word Character (a-z, A-Z, 0-9, _)
\W      - Not a Word Character
\s      - Whitespace (space, tab, newline)
\S      - Not Whitespace (space, tab, newline)

\b      - Word Boundary
\B      - Not a Word Boundary
^       - Beginning of a String
$       - End of a String

[]      - Matches Characters in brackets
[^ ]    - Matches Characters NOT in brackets
|       - Either Or
( )     - Group

Quantifiers:
*       - 0 or More
+       - 1 or More
?       - 0 or One
{3}     - Exact Number
{3,4}   - Range of Numbers (Minimum, Maximum)
'''

In [3]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
Salahuddin11@learnbay.com
321-555-4321
123.555.1234
123*555*1234
123.555.1234
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''

In [1]:
import re

In [10]:
# What you want to match
pattern = re.compile('abc')

# From what text you have to match
matches = pattern.finditer(text_to_search)

for i in matches:
    print(i)

<re.Match object; span=(1, 4), match='abc'>


In [5]:
text_to_search[1:4]

'abc'

In [12]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
Salahuddin11@learnbay.com
321-555-4321
123.555.1234
123*555*1234
123.555.1234
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''

In [13]:
# . dot will extract all the char except a new line

# What you want to match
pattern = re.compile(r'.')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(3, 4), match='c'>
<re.Match object; span=(4, 5), match='d'>
<re.Match object; span=(5, 6), match='e'>
<re.Match object; span=(6, 7), match='f'>
<re.Match object; span=(7, 8), match='g'>
<re.Match object; span=(8, 9), match='h'>
<re.Match object; span=(9, 10), match='i'>
<re.Match object; span=(10, 11), match='j'>
<re.Match object; span=(11, 12), match='k'>
<re.Match object; span=(12, 13), match='l'>
<re.Match object; span=(13, 14), match='m'>
<re.Match object; span=(14, 15), match='n'>
<re.Match object; span=(15, 16), match='o'>
<re.Match object; span=(16, 17), match='p'>
<re.Match object; span=(17, 18), match='q'>
<re.Match object; span=(18, 19), match='u'>
<re.Match object; span=(19, 20), match='r'>
<re.Match object; span=(20, 21), match='t'>
<re.Match object; span=(21, 22), match='u'>
<re.Match object; span=(22, 23), match='v'>
<re.Match object; span=(23, 24), match='w'>
<re.M

In [14]:
# 

# What you want to match
pattern = re.compile(r'\d')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(57, 58), match='3'>
<re.Match object; span=(58, 59), match='2'>
<re.Match object; span=(59, 60), match='1'>
<re.Match object; span=(61, 62), match='5'>
<re.Match object; span=(62, 63), match='5'>
<re.Match object; span=(63, 64), match='5'>
<re.Match object; span=(65, 66), match='4'>
<re.Match object; span=(66, 67), match='3'>
<re.Match object; span=(67, 68), match='2'>
<re.Match object; span=(68, 69), match='1'>
<re.Match object; span=(70, 71), match='1'>
<re.Match object; span=(71, 72), match='2'>
<re.Match object; span=(72, 73), match='3'>
<re.Match object; span=(73, 74), match='4'>
<re.Match object; span=(74, 75), match='5'>
<re.Match object; span=(75, 76), match='6'>
<re.Match object; span=(76, 77), match='7'>
<re.Match object; span=(77, 78), match='8'>
<re.Match object; span=(78, 79), match='9'>
<re.Match object; span=(79, 80), match='0'>
<re.Match object; span=(164, 165), match='1'>
<re.Match object; span=(165, 166), match='1'>
<re.Match object; span=(180,

In [15]:
# 

# What you want to match
pattern = re.compile(r'\D')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(0, 1), match='\n'>
<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(3, 4), match='c'>
<re.Match object; span=(4, 5), match='d'>
<re.Match object; span=(5, 6), match='e'>
<re.Match object; span=(6, 7), match='f'>
<re.Match object; span=(7, 8), match='g'>
<re.Match object; span=(8, 9), match='h'>
<re.Match object; span=(9, 10), match='i'>
<re.Match object; span=(10, 11), match='j'>
<re.Match object; span=(11, 12), match='k'>
<re.Match object; span=(12, 13), match='l'>
<re.Match object; span=(13, 14), match='m'>
<re.Match object; span=(14, 15), match='n'>
<re.Match object; span=(15, 16), match='o'>
<re.Match object; span=(16, 17), match='p'>
<re.Match object; span=(17, 18), match='q'>
<re.Match object; span=(18, 19), match='u'>
<re.Match object; span=(19, 20), match='r'>
<re.Match object; span=(20, 21), match='t'>
<re.Match object; span=(21, 22), match='u'>
<re.Match object; span=(22, 23), match='v'>
<re.Ma

In [46]:
# 

# What you want to match
pattern = re.compile(r'\w')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(3, 4), match='c'>
<re.Match object; span=(4, 5), match='d'>
<re.Match object; span=(5, 6), match='e'>
<re.Match object; span=(6, 7), match='f'>
<re.Match object; span=(7, 8), match='g'>
<re.Match object; span=(8, 9), match='h'>
<re.Match object; span=(9, 10), match='i'>
<re.Match object; span=(10, 11), match='j'>
<re.Match object; span=(11, 12), match='k'>
<re.Match object; span=(12, 13), match='l'>
<re.Match object; span=(13, 14), match='m'>
<re.Match object; span=(14, 15), match='n'>
<re.Match object; span=(15, 16), match='o'>
<re.Match object; span=(16, 17), match='p'>
<re.Match object; span=(17, 18), match='q'>
<re.Match object; span=(18, 19), match='u'>
<re.Match object; span=(19, 20), match='r'>
<re.Match object; span=(20, 21), match='t'>
<re.Match object; span=(21, 22), match='u'>
<re.Match object; span=(22, 23), match='v'>
<re.Match object; span=(23, 24), match='w'>
<re.M

In [16]:
# 

# What you want to match
pattern = re.compile(r'\W')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(0, 1), match='\n'>
<re.Match object; span=(27, 28), match='\n'>
<re.Match object; span=(54, 55), match='\\'>
<re.Match object; span=(56, 57), match='\n'>
<re.Match object; span=(60, 61), match='-'>
<re.Match object; span=(64, 65), match='-'>
<re.Match object; span=(69, 70), match='\n'>
<re.Match object; span=(80, 81), match='\n'>
<re.Match object; span=(83, 84), match=' '>
<re.Match object; span=(88, 89), match='\n'>
<re.Match object; span=(103, 104), match=' '>
<re.Match object; span=(104, 105), match='('>
<re.Match object; span=(109, 110), match=' '>
<re.Match object; span=(112, 113), match=' '>
<re.Match object; span=(115, 116), match=' '>
<re.Match object; span=(123, 124), match=')'>
<re.Match object; span=(124, 125), match=':'>
<re.Match object; span=(125, 126), match='\n'>
<re.Match object; span=(126, 127), match='.'>
<re.Match object; span=(127, 128), match=' '>
<re.Match object; span=(128, 129), match='^'>
<re.Match object; span=(129, 130), match=' '>
<r

In [48]:
# 

# What you want to match
pattern = re.compile(r'\s')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(0, 1), match='\n'>
<re.Match object; span=(27, 28), match='\n'>
<re.Match object; span=(56, 57), match='\n'>
<re.Match object; span=(69, 70), match='\n'>
<re.Match object; span=(80, 81), match='\n'>
<re.Match object; span=(83, 84), match=' '>
<re.Match object; span=(88, 89), match='\n'>
<re.Match object; span=(103, 104), match=' '>
<re.Match object; span=(109, 110), match=' '>
<re.Match object; span=(112, 113), match=' '>
<re.Match object; span=(115, 116), match=' '>
<re.Match object; span=(125, 126), match='\n'>
<re.Match object; span=(127, 128), match=' '>
<re.Match object; span=(129, 130), match=' '>
<re.Match object; span=(131, 132), match=' '>
<re.Match object; span=(133, 134), match=' '>
<re.Match object; span=(135, 136), match=' '>
<re.Match object; span=(137, 138), match=' '>
<re.Match object; span=(139, 140), match=' '>
<re.Match object; span=(141, 142), match=' '>
<re.Match object; span=(143, 144), match=' '>
<re.Match object; span=(145, 146), match=' 

In [18]:
# 

# What you want to match
pattern = re.compile(r'\S')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(3, 4), match='c'>
<re.Match object; span=(4, 5), match='d'>
<re.Match object; span=(5, 6), match='e'>
<re.Match object; span=(6, 7), match='f'>
<re.Match object; span=(7, 8), match='g'>
<re.Match object; span=(8, 9), match='h'>
<re.Match object; span=(9, 10), match='i'>
<re.Match object; span=(10, 11), match='j'>
<re.Match object; span=(11, 12), match='k'>
<re.Match object; span=(12, 13), match='l'>
<re.Match object; span=(13, 14), match='m'>
<re.Match object; span=(14, 15), match='n'>
<re.Match object; span=(15, 16), match='o'>
<re.Match object; span=(16, 17), match='p'>
<re.Match object; span=(17, 18), match='q'>
<re.Match object; span=(18, 19), match='u'>
<re.Match object; span=(19, 20), match='r'>
<re.Match object; span=(20, 21), match='t'>
<re.Match object; span=(21, 22), match='u'>
<re.Match object; span=(22, 23), match='v'>
<re.Match object; span=(23, 24), match='w'>
<re.M

In [21]:
# 

# What you want to match
pattern = re.compile(r'\d\d\d.\d\d\d.\d\d\d\d')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(57, 69), match='321-555-4321'>
<re.Match object; span=(180, 192), match='321-555-4321'>
<re.Match object; span=(193, 205), match='123.555.1234'>
<re.Match object; span=(206, 218), match='123*555*1234'>
<re.Match object; span=(219, 231), match='123.555.1234'>
<re.Match object; span=(232, 244), match='800-555-1234'>
<re.Match object; span=(245, 257), match='900-555-1234'>


In [23]:
a = r'hello\nwo\tld'
print(a)

hello\nwo\tld


# \b      - Word Boundary

In [24]:
string = 'cat catherine catholic wildcat copycat uncatchable'

# What you want to match
pattern = re.compile(r'\bcat') # Starting with cat

# From what text you have to match
matches = pattern.finditer(string)


for i in matches:
    print(i)

<re.Match object; span=(0, 3), match='cat'>
<re.Match object; span=(4, 7), match='cat'>
<re.Match object; span=(14, 17), match='cat'>


In [25]:
string = 'cat catherine catholic wildcat copycat uncatchable'

# What you want to match
pattern = re.compile(r'cat\b') # Ending with cat

# From what text you have to match
matches = pattern.finditer(string)


for i in matches:
    print(i)

<re.Match object; span=(0, 3), match='cat'>
<re.Match object; span=(27, 30), match='cat'>
<re.Match object; span=(35, 38), match='cat'>


In [26]:
string = 'cat catherine catholic wildcat copycat uncatchable'

# What you want to match
pattern = re.compile(r'\bcat\b')

# From what text you have to match
matches = pattern.finditer(string)


for i in matches:
    print(i)

<re.Match object; span=(0, 3), match='cat'>


In [27]:
# \B

string = 'cat catherine catholic wildcat copycat uncatchable'

# What you want to match
pattern = re.compile(r'\Bcat\B')

# From what text you have to match
matches = pattern.finditer(string)


for i in matches:
    print(i)

<re.Match object; span=(41, 44), match='cat'>


In [28]:
# ^

string = 'I love football'

# What you want to match
pattern = re.compile(r'^I') # Starting with I

# From what text you have to match
matches = pattern.finditer(string)


for i in matches:
    print(i)

<re.Match object; span=(0, 1), match='I'>


In [31]:
string = 'I love football'

pattern = re.compile('^l')

matches = pattern.finditer(string)

for i in matches:
    print(i)

In [33]:
# ^

string = 'I love football'

# What you want to match
pattern = re.compile(r'l$') # String ending with 'l'

# From what text you have to match
matches = pattern.finditer(string)


for i in matches:
    print(i)

<re.Match object; span=(14, 15), match='l'>


In [34]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
Salahuddin11@learnbay.com
321-555-4321
123.555.1234
123*555*1234
123.555.1234
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''

In [35]:
# What you want to match
pattern = re.compile(r'[89]\d\d.\d\d\d.\d\d\d\d')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(232, 244), match='800-555-1234'>
<re.Match object; span=(245, 257), match='900-555-1234'>


In [36]:
# What you want to match
pattern = re.compile(r'\d\d\d.\d\d\d.\d\d\d\d')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(57, 69), match='321-555-4321'>
<re.Match object; span=(180, 192), match='321-555-4321'>
<re.Match object; span=(193, 205), match='123.555.1234'>
<re.Match object; span=(206, 218), match='123*555*1234'>
<re.Match object; span=(219, 231), match='123.555.1234'>
<re.Match object; span=(232, 244), match='800-555-1234'>
<re.Match object; span=(245, 257), match='900-555-1234'>


In [37]:
# What you want to match
pattern = re.compile(r'[a-z0-9A-Z]')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(3, 4), match='c'>
<re.Match object; span=(4, 5), match='d'>
<re.Match object; span=(5, 6), match='e'>
<re.Match object; span=(6, 7), match='f'>
<re.Match object; span=(7, 8), match='g'>
<re.Match object; span=(8, 9), match='h'>
<re.Match object; span=(9, 10), match='i'>
<re.Match object; span=(10, 11), match='j'>
<re.Match object; span=(11, 12), match='k'>
<re.Match object; span=(12, 13), match='l'>
<re.Match object; span=(13, 14), match='m'>
<re.Match object; span=(14, 15), match='n'>
<re.Match object; span=(15, 16), match='o'>
<re.Match object; span=(16, 17), match='p'>
<re.Match object; span=(17, 18), match='q'>
<re.Match object; span=(18, 19), match='u'>
<re.Match object; span=(19, 20), match='r'>
<re.Match object; span=(20, 21), match='t'>
<re.Match object; span=(21, 22), match='u'>
<re.Match object; span=(22, 23), match='v'>
<re.Match object; span=(23, 24), match='w'>
<re.M

In [38]:
# What you want to match
pattern = re.compile(r'[^a-z]')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(0, 1), match='\n'>
<re.Match object; span=(27, 28), match='\n'>
<re.Match object; span=(28, 29), match='A'>
<re.Match object; span=(29, 30), match='B'>
<re.Match object; span=(30, 31), match='C'>
<re.Match object; span=(31, 32), match='D'>
<re.Match object; span=(32, 33), match='E'>
<re.Match object; span=(33, 34), match='F'>
<re.Match object; span=(34, 35), match='G'>
<re.Match object; span=(35, 36), match='H'>
<re.Match object; span=(36, 37), match='I'>
<re.Match object; span=(37, 38), match='J'>
<re.Match object; span=(38, 39), match='K'>
<re.Match object; span=(39, 40), match='L'>
<re.Match object; span=(40, 41), match='M'>
<re.Match object; span=(41, 42), match='N'>
<re.Match object; span=(42, 43), match='O'>
<re.Match object; span=(43, 44), match='P'>
<re.Match object; span=(44, 45), match='Q'>
<re.Match object; span=(45, 46), match='R'>
<re.Match object; span=(46, 47), match='S'>
<re.Match object; span=(47, 48), match='T'>
<re.Match object; span=(48, 49),

In [39]:
# What you want to match
pattern = re.compile(r'[bm]at')

# From what text you have to match
matches = pattern.finditer('cat bat fat mat rat')


for i in matches:
    print(i)

<re.Match object; span=(4, 7), match='bat'>
<re.Match object; span=(12, 15), match='mat'>


In [40]:
# What you want to match
pattern = re.compile(r'\d{3}.\d{3}.\d{4}')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(57, 69), match='321-555-4321'>
<re.Match object; span=(180, 192), match='321-555-4321'>
<re.Match object; span=(193, 205), match='123.555.1234'>
<re.Match object; span=(206, 218), match='123*555*1234'>
<re.Match object; span=(219, 231), match='123.555.1234'>
<re.Match object; span=(232, 244), match='800-555-1234'>
<re.Match object; span=(245, 257), match='900-555-1234'>


In [79]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
Salahuddin11@learnbay.com
21-555-4321
123.555.12345
123*555*12343
123.555.12344
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''

In [81]:
print(text_to_search)


abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
Salahuddin11@learnbay.com
21-555-4321
123.555.12345
123*555*12343
123.555.12344
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello



In [82]:
# What you want to match
pattern = re.compile(r'\d{3}.\d{3}.\d{4,5}')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(57, 69), match='321-555-4321'>
<re.Match object; span=(192, 205), match='123.555.12345'>
<re.Match object; span=(206, 219), match='123*555*12343'>
<re.Match object; span=(220, 233), match='123.555.12344'>
<re.Match object; span=(234, 246), match='800-555-1234'>
<re.Match object; span=(247, 259), match='900-555-1234'>


In [ ]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
Salahuddin11@learnbay.com
321-555-4321
123.555.12345
123*555*12343
123.555.12344
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''

In [85]:
# step 1
# What you want to match
pattern = re.compile(r'M')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(40, 41), match='M'>
<re.Match object; span=(89, 90), match='M'>
<re.Match object; span=(261, 262), match='M'>
<re.Match object; span=(273, 274), match='M'>
<re.Match object; span=(282, 283), match='M'>
<re.Match object; span=(291, 292), match='M'>
<re.Match object; span=(305, 306), match='M'>
<re.Match object; span=(311, 312), match='M'>


In [86]:
# step 1
# What you want to match
pattern = re.compile(r'Mr')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(261, 263), match='Mr'>
<re.Match object; span=(273, 275), match='Mr'>
<re.Match object; span=(291, 293), match='Mr'>
<re.Match object; span=(305, 307), match='Mr'>
<re.Match object; span=(311, 313), match='Mr'>


In [114]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
Salahuddin11@learnbay.com
321-555-4321
123.555.12345
123*555*12343
123.555.12344
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''

In [116]:
# step 1
# What you want to match
pattern = re.compile(r'M(r|s|rs).*[A-Z]*[a-z]*')

# From what text you have to match
matches = pattern.finditer(text_to_search)


for i in matches:
    print(i)

<re.Match object; span=(261, 272), match='Mr. Schafer'>
<re.Match object; span=(273, 281), match='Mr Smith'>
<re.Match object; span=(282, 290), match='Ms Davis'>
<re.Match object; span=(291, 304), match='Mrs. Robinson'>
<re.Match object; span=(305, 310), match='Mr. T'>
<re.Match object; span=(311, 319), match='Mr_hello'>


In [1]:
lst = ['akzelxw@hotmail.com',
'elum@@gmail.com', # invalid
'12345akbar.caakaterasu@gmail.com', # invalid
'akarui$kibuno@gmail.com', # invalid
'23545436@hotmail.com', # valid
'ajmeia@yahoo.com',
'ajhnstn87@gmail.com',
'ailuvzhoko4@hotmail.com',
'ailuvzhoko3@hotmail.com',
'ailuvzhoko2@hotmail.com',
'ailuvzhoko@hot123mail.com', # invalid
'aillensiquioco@aol.co.in', # valid
'ahmovic_ines@hotmail.com.in', # invalid
'ahmed__g300@yahoo.com', # invalid
'ahmadjazlan@gmail.com.com', # invalid
'ahmad_ridho19@yahoo.in'] # valid

In [ ]:
# extract all the valid maild ids
# extract valid mail IDs only from gmail.com

In [2]:
e_list = []

for i in lst:
    pattern = re.compile(r'logic')

    # From what text you have to match
    matches = pattern.findall(i)
    e_list.append(matches)

NameError: name 're' is not defined

In [125]:
# step 1
# What you want to match
pattern = re.compile(r'[89]\d\d.\d\d\d.\d\d\d\d')

# From what text you have to match
matches = pattern.findall(text_to_search)
matches

['800-555-1234', '900-555-1234']

In [120]:
print(dir(re))

['A', 'ASCII', 'DEBUG', 'DOTALL', 'I', 'IGNORECASE', 'L', 'LOCALE', 'M', 'MULTILINE', 'Match', 'Pattern', 'RegexFlag', 'S', 'Scanner', 'T', 'TEMPLATE', 'U', 'UNICODE', 'VERBOSE', 'X', '_MAXCACHE', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_cache', '_compile', '_compile_repl', '_expand', '_locale', '_pickle', '_special_chars_map', '_subx', 'compile', 'copyreg', 'enum', 'error', 'escape', 'findall', 'finditer', 'fullmatch', 'functools', 'match', 'purge', 'search', 'split', 'sre_compile', 'sre_parse', 'sub', 'subn', 'template']


# Numpy - Numerical python

- This is a package used for computing and processing of single and multidimensional arrays
- It is written in c
- It can only contain homogenous data

In [ ]:
# 

maths --> matrix
programs ---> arrays
deep learning --> tensors

In [3]:
import numpy as np

# 1. Creating an array using python lis or tuple ussing array function

In [4]:
lst = [1,2,23,4,4,5,6,7]

print(lst , type(lst))

[1, 2, 23, 4, 4, 5, 6, 7] <class 'list'>


In [11]:
lst = [1,2,23,4,4,5,6,7] # 1,8

arr = np.array(lst)

print(arr , type(arr))

[ 1  2 23  4  4  5  6  7] <class 'numpy.ndarray'>


In [12]:
# few important attributes
# size of an array , No of elements in the array

print(arr.size)


# Shape
print(arr.shape)

# dimension

print(arr.ndim)

8
(8,)
1


In [136]:
lst = {1,2,23,4,4,5,6,7} # 1,8

arr = np.array(lst)


print(arr , type(arr))

{1, 2, 4, 5, 6, 7, 23} <class 'numpy.ndarray'>


# 2d

In [13]:
lst = [[1,2] , [3,4] , [5,6]] # 

arr = np.array(lst)


print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
6
2


In [138]:
lst = [[1,2,3],[4,5,6],[4,52,2],[7,4,3]] # 

arr = np.array(lst)


print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 4 52  2]
 [ 7  4  3]]
(4, 3)
12
2


# 3d

In [141]:
lst = [[[1,2] , [3,4] , [5,6]] ,[[9,6] , [2,8] , [5,6]]]

arr = np.array(lst)

# 3 rows , 2 columns and the depth is 2
print(arr)
print(arr.shape)
# print(arr.size)
print(arr.ndim)

[[[1 2]
  [3 4]
  [5 6]]

 [[9 6]
  [2 8]
  [5 6]]]
(2, 3, 2)
3


In [14]:
lst = [[[1,2,3],[4,5,6],[4,52,2],[7,4,3]],[[1,2,3],[4,5,6],[4,52,2],[7,4,3]],[[1,2,3],[4,5,6],[4,52,2],[7,4,3]]] 

arr = np.array(lst)


print(arr)
print(arr.shape) # 3, 4, 3
print(arr.size)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 4 52  2]
  [ 7  4  3]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 4 52  2]
  [ 7  4  3]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 4 52  2]
  [ 7  4  3]]]
(3, 4, 3)
36
3


In [147]:
np.arange(36).reshape((4,3,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [ ]:
[]--> 1D
[[] , []] --> 2D
[[[] , []] , [[] , []]] ---> 3D

# 2. Create an array arrange function

In [15]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [149]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
np.arange(0,10 , 2)

array([0, 2, 4, 6, 8])

# Linspace

In [ ]:
0,10


20

In [151]:
np.linspace(1,10 , 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [175]:
1- 1.47368421

-0.47368421000000005

In [176]:
 1.47368421 - 1.94736842

-0.47368421000000005

In [174]:
np.linspace(0,100 , 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

# Zeros and zeros like

In [16]:
np.zeros((0,10) , dtype = int)

array([], shape=(0, 10), dtype=int64)

In [154]:
np.zeros((2,4) , dtype = int) # 2, 4

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
np.zeros((4,2,6) , dtype = int) # 4,2,6

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [165]:
# zerolike 

lst = [[1,2] , [3,4] , [5,6]] # 

arr = np.array(lst)

np.zeros_like(arr)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [166]:
# ones and ones like

np.ones((2,4) , dtype = int) # 2, 4

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [167]:
# zerolike 

lst = [[1,2] , [3,4] , [5,6]] # 

arr = np.array(lst)

np.ones_like(arr)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [168]:
# identity matrix

- Sqaure matrics 
# dig as 1

In [170]:
lst = [[1,2] , [3,4]] # 

arr = np.array(lst)
arr

array([[1, 2],
       [3, 4]])

In [171]:
np.identity(4 , dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [178]:
lst = [11 , 12 , 1.2]

arr = np.array(lst)
arr

array([11. , 12. ,  1.2])

# Create an array with random